package com.example.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

enum class ThemeCategory(val title: String) {
    SINGLE_COLOR("Single-Color Themes"),
    MULTI_COLOR("Multi-Color Combinations")
}

/**
 * Complete Professional Color Identity & Palette System.
 * Each theme defines a coordinated Material 3 ColorScheme for both Light Mode and Dark Mode,
 * ensuring high-contrast readability, semantic separation, and a distinct visual identity.
 */
enum class AppColorTheme(
    val id: String,
    val displayName: String,
    val category: ThemeCategory,
    val previewColors: List<Color>,
    val lightColorScheme: ColorScheme,
    val darkColorScheme: ColorScheme
) {
    // =========================================================================
    // A. SINGLE-COLOR FAMILY THEMES (12 Coordinated Palettes)
    // =========================================================================

    PROFESSIONAL_BLUE(
        id = "professional_blue",
        displayName = "Professional Blue",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFF4F46E5), Color(0xFF0284C7), Color(0xFF0D9488)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF4F46E5),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFEEF2FF),
            onPrimaryContainer = Color(0xFF312E81),
            secondary = Color(0xFF0284C7),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE0F2FE),
            onSecondaryContainer = Color(0xFF0369A1),
            tertiary = Color(0xFF0D9488),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFCCFBF1),
            onTertiaryContainer = Color(0xFF115E59),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = LightSurfaceVariant,
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = LightOutline,
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF818CF8),
            onPrimary = Color(0xFF0F172A),
            primaryContainer = Color(0xFF3730A3),
            onPrimaryContainer = Color(0xFFE0E7FF),
            secondary = Color(0xFF38BDF8),
            onSecondary = Color(0xFF0F172A),
            secondaryContainer = Color(0xFF0369A1),
            onSecondaryContainer = Color(0xFFE0F2FE),
            tertiary = Color(0xFF2DD4BF),
            onTertiary = Color(0xFF0F172A),
            tertiaryContainer = Color(0xFF115E59),
            onTertiaryContainer = Color(0xFFCCFBF1),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = DarkSurfaceVariant,
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = DarkOutline,
            error = ErrorColor,
            onError = Color.White
        )
    ),

    ROYAL_PURPLE(
        id = "royal_purple",
        displayName = "Royal Purple",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFF7C3AED), Color(0xFF6D28D9), Color(0xFFA855F7)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF7C3AED),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFF3E8FF),
            onPrimaryContainer = Color(0xFF581C87),
            secondary = Color(0xFF6D28D9),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFEDE9FE),
            onSecondaryContainer = Color(0xFF4C1D95),
            tertiary = Color(0xFFA855F7),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFFAF5FF),
            onTertiaryContainer = Color(0xFF6B21A8),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFF5F3FF),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFE9D5FF),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFFA78BFA),
            onPrimary = Color(0xFF1E1B4B),
            primaryContainer = Color(0xFF581C87),
            onPrimaryContainer = Color(0xFFF3E8FF),
            secondary = Color(0xFFC084FC),
            onSecondary = Color(0xFF1E1B4B),
            secondaryContainer = Color(0xFF4C1D95),
            onSecondaryContainer = Color(0xFFEDE9FE),
            tertiary = Color(0xFFE879F9),
            onTertiary = Color(0xFF1E1B4B),
            tertiaryContainer = Color(0xFF701A75),
            onTertiaryContainer = Color(0xFFFAE8FF),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF241C35),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF4C1D95),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    EMERALD_GREEN(
        id = "emerald_green",
        displayName = "Emerald Green",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFF059669), Color(0xFF047857), Color(0xFF10B981)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF059669),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFD1FAE5),
            onPrimaryContainer = Color(0xFF064E3B),
            secondary = Color(0xFF047857),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFA7F3D0),
            onSecondaryContainer = Color(0xFF065F46),
            tertiary = Color(0xFF10B981),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFECFDF5),
            onTertiaryContainer = Color(0xFF047857),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFF0FDF4),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFA7F3D0),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF34D399),
            onPrimary = Color(0xFF022C22),
            primaryContainer = Color(0xFF064E3B),
            onPrimaryContainer = Color(0xFFD1FAE5),
            secondary = Color(0xFF6EE7B7),
            onSecondary = Color(0xFF022C22),
            secondaryContainer = Color(0xFF065F46),
            onSecondaryContainer = Color(0xFFA7F3D0),
            tertiary = Color(0xFFA7F3D0),
            onTertiary = Color(0xFF022C22),
            tertiaryContainer = Color(0xFF047857),
            onTertiaryContainer = Color(0xFFECFDF5),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF132B20),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF065F46),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    PREMIUM_TEAL(
        id = "premium_teal",
        displayName = "Premium Teal",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFF0D9488), Color(0xFF0F766E), Color(0xFF14B8A6)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF0D9488),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFCCFBF1),
            onPrimaryContainer = Color(0xFF115E59),
            secondary = Color(0xFF0F766E),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFF99F6E4),
            onSecondaryContainer = Color(0xFF134E4A),
            tertiary = Color(0xFF14B8A6),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFF0FDFA),
            onTertiaryContainer = Color(0xFF0F766E),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFF0FDFA),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFF99F6E4),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF2DD4BF),
            onPrimary = Color(0xFF042F2E),
            primaryContainer = Color(0xFF115E59),
            onPrimaryContainer = Color(0xFFCCFBF1),
            secondary = Color(0xFF5EEAD4),
            onSecondary = Color(0xFF042F2E),
            secondaryContainer = Color(0xFF134E4A),
            onSecondaryContainer = Color(0xFF99F6E4),
            tertiary = Color(0xFF99F6E4),
            onTertiary = Color(0xFF042F2E),
            tertiaryContainer = Color(0xFF0F766E),
            onTertiaryContainer = Color(0xFFF0FDFA),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF132D2B),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF134E4A),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    DEEP_INDIGO(
        id = "deep_indigo",
        displayName = "Deep Indigo",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFF4338CA), Color(0xFF3730A3), Color(0xFF6366F1)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF4338CA),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFE0E7FF),
            onPrimaryContainer = Color(0xFF312E81),
            secondary = Color(0xFF3730A3),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFC7D2FE),
            onSecondaryContainer = Color(0xFF1E1B4B),
            tertiary = Color(0xFF6366F1),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFEEF2FF),
            onTertiaryContainer = Color(0xFF3730A3),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFF5F7FF),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFC7D2FE),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF818CF8),
            onPrimary = Color(0xFF1E1B4B),
            primaryContainer = Color(0xFF312E81),
            onPrimaryContainer = Color(0xFFE0E7FF),
            secondary = Color(0xFFA5B4FC),
            onSecondary = Color(0xFF1E1B4B),
            secondaryContainer = Color(0xFF1E1B4B),
            onSecondaryContainer = Color(0xFFC7D2FE),
            tertiary = Color(0xFFC7D2FE),
            onTertiary = Color(0xFF1E1B4B),
            tertiaryContainer = Color(0xFF3730A3),
            onTertiaryContainer = Color(0xFFEEF2FF),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF1A1F36),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF312E81),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    PROFESSIONAL_ORANGE(
        id = "professional_orange",
        displayName = "Professional Orange",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFFEA580C), Color(0xFFC2410C), Color(0xFFF97316)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFFEA580C),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFFEDD5),
            onPrimaryContainer = Color(0xFF7C2D12),
            secondary = Color(0xFFC2410C),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFED7AA),
            onSecondaryContainer = Color(0xFF9A3412),
            tertiary = Color(0xFFF97316),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFFFF7ED),
            onTertiaryContainer = Color(0xFFC2410C),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFFFF7ED),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFFED7AA),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFFFB923C),
            onPrimary = Color(0xFF431407),
            primaryContainer = Color(0xFF7C2D12),
            onPrimaryContainer = Color(0xFFFFEDD5),
            secondary = Color(0xFFFDBA74),
            onSecondary = Color(0xFF431407),
            secondaryContainer = Color(0xFF9A3412),
            onSecondaryContainer = Color(0xFFFED7AA),
            tertiary = Color(0xFFFED7AA),
            onTertiary = Color(0xFF431407),
            tertiaryContainer = Color(0xFFC2410C),
            onTertiaryContainer = Color(0xFFFFF7ED),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF2C1E18),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF7C2D12),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    CRIMSON(
        id = "crimson",
        displayName = "Crimson",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFFBE123C), Color(0xFF9F1239), Color(0xFFE11D48)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFFBE123C),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFFE4E6),
            onPrimaryContainer = Color(0xFF881337),
            secondary = Color(0xFF9F1239),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFECDD3),
            onSecondaryContainer = Color(0xFF4C0519),
            tertiary = Color(0xFFE11D48),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFFFF1F2),
            onTertiaryContainer = Color(0xFF9F1239),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFFFF1F2),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFFECDD3),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFFFB7185),
            onPrimary = Color(0xFF4C0519),
            primaryContainer = Color(0xFF881337),
            onPrimaryContainer = Color(0xFFFFE4E6),
            secondary = Color(0xFFFDA4AF),
            onSecondary = Color(0xFF4C0519),
            secondaryContainer = Color(0xFF9F1239),
            onSecondaryContainer = Color(0xFFFECDD3),
            tertiary = Color(0xFFFECDD3),
            onTertiary = Color(0xFF4C0519),
            tertiaryContainer = Color(0xFFBE123C),
            onTertiaryContainer = Color(0xFFFFF1F2),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF2E1920),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF881337),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    CYAN(
        id = "cyan",
        displayName = "Cyan",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFF0891B2), Color(0xFF0E7490), Color(0xFF06B6D4)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF0891B2),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFCFFAFE),
            onPrimaryContainer = Color(0xFF164E63),
            secondary = Color(0xFF0E7490),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFA5F3FC),
            onSecondaryContainer = Color(0xFF155E75),
            tertiary = Color(0xFF06B6D4),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFECFEFF),
            onTertiaryContainer = Color(0xFF0E7490),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFECFEFF),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFA5F3FC),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF22D3EE),
            onPrimary = Color(0xFF083344),
            primaryContainer = Color(0xFF164E63),
            onPrimaryContainer = Color(0xFFCFFAFE),
            secondary = Color(0xFF67E8F9),
            onSecondary = Color(0xFF083344),
            secondaryContainer = Color(0xFF155E75),
            onSecondaryContainer = Color(0xFFA5F3FC),
            tertiary = Color(0xFFA5F3FC),
            onTertiary = Color(0xFF083344),
            tertiaryContainer = Color(0xFF0E7490),
            onTertiaryContainer = Color(0xFFECFEFF),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF122C35),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF164E63),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    ROSE(
        id = "rose",
        displayName = "Rose",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFFE11D48), Color(0xFFBE185D), Color(0xFFF43F5E)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFFE11D48),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFFE4E6),
            onPrimaryContainer = Color(0xFF881337),
            secondary = Color(0xFFBE185D),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFCE7F3),
            onSecondaryContainer = Color(0xFF831843),
            tertiary = Color(0xFFF43F5E),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFFFF1F2),
            onTertiaryContainer = Color(0xFF9F1239),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFFFF1F2),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFFECDD3),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFFFB7185),
            onPrimary = Color(0xFF4C0519),
            primaryContainer = Color(0xFF881337),
            onPrimaryContainer = Color(0xFFFFE4E6),
            secondary = Color(0xFFF472B6),
            onSecondary = Color(0xFF500724),
            secondaryContainer = Color(0xFF831843),
            onSecondaryContainer = Color(0xFFFCE7F3),
            tertiary = Color(0xFFFDA4AF),
            onTertiary = Color(0xFF4C0519),
            tertiaryContainer = Color(0xFFBE185D),
            onTertiaryContainer = Color(0xFFFFF1F2),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF2E1924),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF881337),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    AMBER(
        id = "amber",
        displayName = "Amber",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFFD97706), Color(0xFFB45309), Color(0xFFF59E0B)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFFD97706),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFEF3C7),
            onPrimaryContainer = Color(0xFF78350F),
            secondary = Color(0xFFB45309),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFDE68A),
            onSecondaryContainer = Color(0xFF92400E),
            tertiary = Color(0xFFF59E0B),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFFFFBEB),
            onTertiaryContainer = Color(0xFFB45309),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFFFFBEB),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFFDE68A),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFFFBBF24),
            onPrimary = Color(0xFF451A03),
            primaryContainer = Color(0xFF78350F),
            onPrimaryContainer = Color(0xFFFEF3C7),
            secondary = Color(0xFFFCD34D),
            onSecondary = Color(0xFF451A03),
            secondaryContainer = Color(0xFF92400E),
            onSecondaryContainer = Color(0xFFFDE68A),
            tertiary = Color(0xFFFDE68A),
            onTertiary = Color(0xFF451A03),
            tertiaryContainer = Color(0xFFB45309),
            onTertiaryContainer = Color(0xFFFFFBEB),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF2D2316),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF78350F),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    NAVY(
        id = "navy",
        displayName = "Navy",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFF1E3A8A), Color(0xFF172554), Color(0xFF3B82F6)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF1E3A8A),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFDBEAFE),
            onPrimaryContainer = Color(0xFF1E3A8A),
            secondary = Color(0xFF1D4ED8),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFBFDBFE),
            onSecondaryContainer = Color(0xFF172554),
            tertiary = Color(0xFF3B82F6),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFEFF6FF),
            onTertiaryContainer = Color(0xFF1E40AF),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFF0F6FF),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFBFDBFE),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF60A5FA),
            onPrimary = Color(0xFF0F172A),
            primaryContainer = Color(0xFF1E3A8A),
            onPrimaryContainer = Color(0xFFDBEAFE),
            secondary = Color(0xFF93C5FD),
            onSecondary = Color(0xFF0F172A),
            secondaryContainer = Color(0xFF172554),
            onSecondaryContainer = Color(0xFFBFDBFE),
            tertiary = Color(0xFFBFDBFE),
            onTertiary = Color(0xFF0F172A),
            tertiaryContainer = Color(0xFF1E40AF),
            onTertiaryContainer = Color(0xFFEFF6FF),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF14223A),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF1E3A8A),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    SLATE(
        id = "slate",
        displayName = "Slate",
        category = ThemeCategory.SINGLE_COLOR,
        previewColors = listOf(Color(0xFF475569), Color(0xFF334155), Color(0xFF64748B)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF475569),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFF1F5F9),
            onPrimaryContainer = Color(0xFF0F172A),
            secondary = Color(0xFF334155),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE2E8F0),
            onSecondaryContainer = Color(0xFF1E293B),
            tertiary = Color(0xFF64748B),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFF8FAFC),
            onTertiaryContainer = Color(0xFF334155),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFF1F5F9),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFCBD5E1),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF94A3B8),
            onPrimary = Color(0xFF0F172A),
            primaryContainer = Color(0xFF334155),
            onPrimaryContainer = Color(0xFFF1F5F9),
            secondary = Color(0xFFCBD5E1),
            onSecondary = Color(0xFF0F172A),
            secondaryContainer = Color(0xFF1E293B),
            onSecondaryContainer = Color(0xFFE2E8F0),
            tertiary = Color(0xFFE2E8F0),
            onTertiary = Color(0xFF0F172A),
            tertiaryContainer = Color(0xFF475569),
            onTertiaryContainer = Color(0xFFF8FAFC),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF1E293B),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF475569),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    // =========================================================================
    // B. MULTI-COLOR COMBINATION THEMES (8 Coordinated Palettes)
    // =========================================================================

    BLUE_INDIGO(
        id = "blue_indigo",
        displayName = "Blue + Indigo",
        category = ThemeCategory.MULTI_COLOR,
        previewColors = listOf(Color(0xFF2563EB), Color(0xFF4F46E5), Color(0xFF06B6D4)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF2563EB),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFDBEAFE),
            onPrimaryContainer = Color(0xFF1E40AF),
            secondary = Color(0xFF4F46E5),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFEEF2FF),
            onSecondaryContainer = Color(0xFF312E81),
            tertiary = Color(0xFF06B6D4),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFCFFAFE),
            onTertiaryContainer = Color(0xFF164E63),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFEFF6FF),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFBFDBFE),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF60A5FA),
            onPrimary = Color(0xFF0F172A),
            primaryContainer = Color(0xFF1E40AF),
            onPrimaryContainer = Color(0xFFDBEAFE),
            secondary = Color(0xFF818CF8),
            onSecondary = Color(0xFF0F172A),
            secondaryContainer = Color(0xFF3730A3),
            onSecondaryContainer = Color(0xFFEEF2FF),
            tertiary = Color(0xFF22D3EE),
            onTertiary = Color(0xFF0F172A),
            tertiaryContainer = Color(0xFF164E63),
            onTertiaryContainer = Color(0xFFCFFAFE),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF16203B),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF1E40AF),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    PURPLE_PINK(
        id = "purple_pink",
        displayName = "Purple + Pink",
        category = ThemeCategory.MULTI_COLOR,
        previewColors = listOf(Color(0xFF7C3AED), Color(0xFFDB2777), Color(0xFFA855F7)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF7C3AED),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFF3E8FF),
            onPrimaryContainer = Color(0xFF581C87),
            secondary = Color(0xFFDB2777),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFCE7F3),
            onSecondaryContainer = Color(0xFF831843),
            tertiary = Color(0xFFA855F7),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFFAF5FF),
            onTertiaryContainer = Color(0xFF6B21A8),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFFAF5FF),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFFBCFE8),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFFA78BFA),
            onPrimary = Color(0xFF1E1B4B),
            primaryContainer = Color(0xFF581C87),
            onPrimaryContainer = Color(0xFFF3E8FF),
            secondary = Color(0xFFF472B6),
            onSecondary = Color(0xFF500724),
            secondaryContainer = Color(0xFF831843),
            onSecondaryContainer = Color(0xFFFCE7F3),
            tertiary = Color(0xFFC084FC),
            onTertiary = Color(0xFF1E1B4B),
            tertiaryContainer = Color(0xFF6B21A8),
            onTertiaryContainer = Color(0xFFFAF5FF),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF281932),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF581C87),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    TEAL_EMERALD(
        id = "teal_emerald",
        displayName = "Teal + Emerald",
        category = ThemeCategory.MULTI_COLOR,
        previewColors = listOf(Color(0xFF0D9488), Color(0xFF059669), Color(0xFF34D399)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF0D9488),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFCCFBF1),
            onPrimaryContainer = Color(0xFF115E59),
            secondary = Color(0xFF059669),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFD1FAE5),
            onSecondaryContainer = Color(0xFF064E3B),
            tertiary = Color(0xFF34D399),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFECFDF5),
            onTertiaryContainer = Color(0xFF047857),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFF0FDFA),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFA7F3D0),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF2DD4BF),
            onPrimary = Color(0xFF042F2E),
            primaryContainer = Color(0xFF115E59),
            onPrimaryContainer = Color(0xFFCCFBF1),
            secondary = Color(0xFF34D399),
            onSecondary = Color(0xFF022C22),
            secondaryContainer = Color(0xFF064E3B),
            onSecondaryContainer = Color(0xFFD1FAE5),
            tertiary = Color(0xFF6EE7B7),
            onTertiary = Color(0xFF022C22),
            tertiaryContainer = Color(0xFF047857),
            onTertiaryContainer = Color(0xFFECFDF5),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF132E27),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF115E59),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    BLUE_CYAN(
        id = "blue_cyan",
        displayName = "Blue + Cyan",
        category = ThemeCategory.MULTI_COLOR,
        previewColors = listOf(Color(0xFF1D4ED8), Color(0xFF0891B2), Color(0xFF38BDF8)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF1D4ED8),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFDBEAFE),
            onPrimaryContainer = Color(0xFF1E3A8A),
            secondary = Color(0xFF0891B2),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFCFFAFE),
            onSecondaryContainer = Color(0xFF164E63),
            tertiary = Color(0xFF38BDF8),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFE0F2FE),
            onTertiaryContainer = Color(0xFF0369A1),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFF0F9FF),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFA5F3FC),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF60A5FA),
            onPrimary = Color(0xFF0F172A),
            primaryContainer = Color(0xFF1E3A8A),
            onPrimaryContainer = Color(0xFFDBEAFE),
            secondary = Color(0xFF22D3EE),
            onSecondary = Color(0xFF083344),
            secondaryContainer = Color(0xFF164E63),
            onSecondaryContainer = Color(0xFFCFFAFE),
            tertiary = Color(0xFF7DD3FC),
            onTertiary = Color(0xFF083344),
            tertiaryContainer = Color(0xFF0369A1),
            onTertiaryContainer = Color(0xFFE0F2FE),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF132737),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF1E3A8A),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    ORANGE_AMBER(
        id = "orange_amber",
        displayName = "Orange + Amber",
        category = ThemeCategory.MULTI_COLOR,
        previewColors = listOf(Color(0xFFEA580C), Color(0xFFD97706), Color(0xFFF97316)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFFEA580C),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFFEDD5),
            onPrimaryContainer = Color(0xFF7C2D12),
            secondary = Color(0xFFD97706),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFEF3C7),
            onSecondaryContainer = Color(0xFF78350F),
            tertiary = Color(0xFFF97316),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFFFF7ED),
            onTertiaryContainer = Color(0xFF9A3412),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFFFF7ED),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFFED7AA),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFFFB923C),
            onPrimary = Color(0xFF431407),
            primaryContainer = Color(0xFF7C2D12),
            onPrimaryContainer = Color(0xFFFFEDD5),
            secondary = Color(0xFFFBBF24),
            onSecondary = Color(0xFF451A03),
            secondaryContainer = Color(0xFF78350F),
            onSecondaryContainer = Color(0xFFFEF3C7),
            tertiary = Color(0xFFFDBA74),
            onTertiary = Color(0xFF431407),
            tertiaryContainer = Color(0xFF9A3412),
            onTertiaryContainer = Color(0xFFFFF7ED),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF2F2018),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF7C2D12),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    NAVY_PURPLE(
        id = "navy_purple",
        displayName = "Navy + Purple",
        category = ThemeCategory.MULTI_COLOR,
        previewColors = listOf(Color(0xFF1E3A8A), Color(0xFF7C3AED), Color(0xFF6366F1)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF1E3A8A),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFDBEAFE),
            onPrimaryContainer = Color(0xFF1E3A8A),
            secondary = Color(0xFF7C3AED),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFF3E8FF),
            onSecondaryContainer = Color(0xFF581C87),
            tertiary = Color(0xFF6366F1),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFEEF2FF),
            onTertiaryContainer = Color(0xFF3730A3),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFF5F7FF),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFC7D2FE),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF60A5FA),
            onPrimary = Color(0xFF0F172A),
            primaryContainer = Color(0xFF1E3A8A),
            onPrimaryContainer = Color(0xFFDBEAFE),
            secondary = Color(0xFFA78BFA),
            onSecondary = Color(0xFF1E1B4B),
            secondaryContainer = Color(0xFF581C87),
            onSecondaryContainer = Color(0xFFF3E8FF),
            tertiary = Color(0xFF818CF8),
            onTertiary = Color(0xFF1E1B4B),
            tertiaryContainer = Color(0xFF3730A3),
            onTertiaryContainer = Color(0xFFEEF2FF),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF1A1F3B),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF1E3A8A),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    EMERALD_TEAL(
        id = "emerald_teal",
        displayName = "Emerald + Teal",
        category = ThemeCategory.MULTI_COLOR,
        previewColors = listOf(Color(0xFF059669), Color(0xFF0D9488), Color(0xFF2DD4BF)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFF059669),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFD1FAE5),
            onPrimaryContainer = Color(0xFF064E3B),
            secondary = Color(0xFF0D9488),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFCCFBF1),
            onSecondaryContainer = Color(0xFF115E59),
            tertiary = Color(0xFF2DD4BF),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFF0FDFA),
            onTertiaryContainer = Color(0xFF0F766E),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFF0FDF4),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFF99F6E4),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFF34D399),
            onPrimary = Color(0xFF022C22),
            primaryContainer = Color(0xFF064E3B),
            onPrimaryContainer = Color(0xFFD1FAE5),
            secondary = Color(0xFF2DD4BF),
            onSecondary = Color(0xFF042F2E),
            secondaryContainer = Color(0xFF115E59),
            onSecondaryContainer = Color(0xFFCCFBF1),
            tertiary = Color(0xFF5EEAD4),
            onTertiary = Color(0xFF042F2E),
            tertiaryContainer = Color(0xFF0F766E),
            onTertiaryContainer = Color(0xFFF0FDFA),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF132D26),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF064E3B),
            error = ErrorColor,
            onError = Color.White
        )
    ),

    CRIMSON_ROSE(
        id = "crimson_rose",
        displayName = "Crimson + Rose",
        category = ThemeCategory.MULTI_COLOR,
        previewColors = listOf(Color(0xFFBE123C), Color(0xFFE11D48), Color(0xFFFB7185)),
        lightColorScheme = lightColorScheme(
            primary = Color(0xFFBE123C),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFFE4E6),
            onPrimaryContainer = Color(0xFF881337),
            secondary = Color(0xFFE11D48),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFCE7F3),
            onSecondaryContainer = Color(0xFF831843),
            tertiary = Color(0xFFFB7185),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFFFF1F2),
            onTertiaryContainer = Color(0xFF9F1239),
            background = LightBackground,
            onBackground = LightOnSurface,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = Color(0xFFFFF1F2),
            onSurfaceVariant = LightOnSurfaceVariant,
            outline = Color(0xFFFECDD3),
            error = ErrorColor,
            onError = Color.White
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xFFFB7185),
            onPrimary = Color(0xFF4C0519),
            primaryContainer = Color(0xFF881337),
            onPrimaryContainer = Color(0xFFFFE4E6),
            secondary = Color(0xFFFDA4AF),
            onSecondary = Color(0xFF4C0519),
            secondaryContainer = Color(0xFF9F1239),
            onSecondaryContainer = Color(0xFFFECDD3),
            tertiary = Color(0xFFF472B6),
            onTertiary = Color(0xFF500724),
            tertiaryContainer = Color(0xFF831843),
            onTertiaryContainer = Color(0xFFFCE7F3),
            background = DarkBackground,
            onBackground = DarkOnSurface,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = Color(0xFF2F1822),
            onSurfaceVariant = DarkOnSurfaceVariant,
            outline = Color(0xFF881337),
            error = ErrorColor,
            onError = Color.White
        )
    );

    companion object {
        fun fromId(id: String?): AppColorTheme {
            return entries.firstOrNull { it.id.equals(id, ignoreCase = true) } ?: PROFESSIONAL_BLUE
        }
    }
}
